### ISSUE TITLE
Kubectl download failed

### ISSUE THREAD

**Issue by spagno** [aws-quickstart/quickstart-vmware-tanzu-application-platform#104]
Hello,
I was trying taskcat with the --no-delete option and I saw that tap wasn't installed. Looking at the logs i get:
+ aws s3 cp --no-progress s3://amazon-eks/1.23.7/2022-06-29/bin/linux/amd64/kubectl ./kubectl
download failed: s3://amazon-eks/1.23.7/2022-06-29/bin/linux/amd64/kubectl to ./kubectl An error occurred (IllegalLocationConstraintException) when calling the GetObject operation: The us-west-2 location constraint is incompatible for the region specific endpoint this request was sent to.

I'm trying to setup it in eu-south-1 region.

I'm sure I already setup TAP in this region with the old template not using taskcat

regards

**Comment by tlindsay42** [comment]
@satya-dillikar and/or @spagno Are you able to duplicate if you set the region to `us-west-2` with the [`--region` parameter](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/cp.html) on [Lines 1380-1381](https://github.com/aws-quickstart/quickstart-vmware-tanzu-application-platform/blob/main/templates/aws-tap-entrypoint-existing-vpc.template.yaml#L1380-L1381)? All of the other awscli s3 cp calls in the user-data script use buckets local to that region, so they shouldn't need to be updated. Also, this hasn't been necessary in other regions in previous testing (including GovCloud).

Alternatively, try updating this to a `wget` or `curl` statement to download the file over the internet ([example](https://docs.aws.amazon.com/eks/latest/userguide/install-kubectl.html)) instead of over a VPC gateway S3 endpoint. My intent with this implementation was to minimize billable outbound internet calls, but the data transfer required for this file is trivial. 

If either fixes it, send over a PR.

**Comment by satya-dillikar** [comment]
@spagno , I was able to change the region in .taskcat.yml and were able to successfully upload and test  in us-west and us-east regions.

Try changing the region in .taskcat.yml and let us know your findings as Troy suggested. 
Thanks
Satya

**Comment by matteowiz** [comment]
Hi,

I'm getting the same problem trying installing tap in eu-south-1 region. How can I fix this?
Thanks
--
matteo

**Comment by leclaist** [comment]
@matteowiz is the region set to eu-south-1 in your .taskcat.yml file?

**Comment by tlindsay42** [comment]
Or are you deploying via the [CloudFormation management console link](https://fwd.aws/DJ34n?) ([reference](https://aws-quickstart.github.io/quickstart-vmware-tanzu-application-platform/#_deployment_options))? Or something else?

**Comment by satya-dillikar** [comment]
@leclaist ,

Yes, you can update the region as eu-south-1 in your .taskcat file or manually deploy it in the eu-south-1 region.

The fix is to 

1.  replace cloud-init.sh:
      line: aws s3 cp --no-progress "s3://amazon-eks/${AwsKubectlVersion}/bin/linux/$arch/kubectl" ./kubectl
      with 
      curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.24.10/2023-01-30/bin/linux/amd64/kubectl
      [Note: parameterize correct version and arch]
    
      and 

1. test in the eu-south-1 region.

HTH
Satya

**Comment by matteowiz** [comment]
@leclaist Yes I'm using the CloudFormation Management Console. 

How can I edit this script? Do I have to import all the files into a personal bucket and run from there?

Thanks
--
matteo

**Comment by tlindsay42** [comment]
@matteowiz Minor misunderstanding on our end. You don't need to, but if you want, you can add the `eu-south-1` region to [one of the tests in the `./.taskcat.yml` config file](https://github.com/aws-quickstart/quickstart-vmware-tanzu-application-platform/blob/b1acb6e42a9931c2a5cb1369c830013b11dd17f3/.taskcat.yml#L28-L38) and deploy via [taskcat](https://aws-ia.github.io/taskcat/). This tool is primarily intended for maintainers, contributors, and CI/CD though. Thank you for your feedback and confirming your deployment method. @leclaist is working on duplicating the issue. Thanks!

**Comment by hoegaarden** [comment]
This has been adressed [here](https://github.com/aws-quickstart/quickstart-vmware-tanzu-application-platform/blob/2c92d99369a41875d75825236432d0a355b138dc/tap-setup-scripts/src/cloud-init.sh#L65-L66). We are also running the internal CI against `eu-south-1` (amongst other regions) and don't see issues re. the `kubectl` download anymore. So I think we are good to close this.
@tlindsay42
